### ISSUE TITLE
list minimum python requirement in README

### ISSUE THREAD

**Issue by obilodeau** [delvelabs/tachyon#3]
Trying out tachyon (in front of 30 students ;) ) for the first time on OSX (10.5) and it fails with:

``` shell
$ python tachyon.py 
Traceback (most recent call last):
  File "tachyon.py", line 23, in <module>
    from core import conf, database, loaders, utils
  File "/Users/olivier/src/tachyon/core/loaders.py", line 35
    except SyntaxError as (errno, strerror):
                        ^
```

I'm pretty sure this is because my OSX carries an ancient version of python (2.5.1).

My suggestion is: can you list minimum requirements in the README? or maybe the script can require a minimum python version (I know you can do that in perl). ;)

Thanks for the great program!

p.s.: compiling python 2.7 through mac ports

**Comment by gabtremblay** [comment]
Fixed, requirements are now in README and checked at code level.
