### ISSUE TITLE
incompatibility with tee

### ISSUE THREAD

**Issue by obilodeau** [delvelabs/tachyon#4]
I don't know how you do your console output but it breaks tee (which I've never seen broken in my short life).

For example, a command like this one:

```
$ ./tachyon.py -w 1 http://mydomain.com 2>&1 | tee ~/tachyon.log
```

should output to both the console and in the log file. Now there's nothing in both (but maybe there will once the scan is done?).

Tee is is very useful for example if I start a scan and I'm not sure if my computer will go to sleep (wife's unplug it), crash or anything. Or even maybe scanning from home and pushing log into dropbox. etc.

Let me know if you want to try anything.

**Comment by gabtremblay** [comment]
Problem was due to a deadlock on sysout, this is now fixed. However, you should use tee -i to make sure the ctrl+c signal is passed down to tachyon instead of being caugh by tee.
